### ISSUE TITLE
Exception "907135003: client api invalid" on Google device

### ISSUE THREAD

**Issue by aw4git** [bluesource/ChoiceSDK#10]
Hi,
When starting my application on a standard Google Pixel 4a (Android 11), I always have this exception at startup.
I am using ChoiceSDK for Push management.
I have this exception even if doing nothing with ChoiceSDK. I mean even if I don't initialize it ...
I don't have this exception on Huawei device supporting HMS.

```
2021-06-17 11:38:54.879 31399-31399/com.chacon.dioone I/HMSSDK_PackageNameManager: CheckUpdateCallBack status is 3
2021-06-17 11:38:54.880 31399-31399/com.chacon.dioone I/HMSSDK_HuaweiApiAvailabilityImpl: Enter getResolveErrorPendingIntent, errorCode: 1 requestCode: 0
2021-06-17 11:38:54.881 31399-31399/com.chacon.dioone I/HMSSDK_HuaweiApiAvailabilityImpl: Enter getResolveErrorIntent, errorCode: 1
2021-06-17 11:38:54.884 31399-31399/com.chacon.dioone E/HMSSDK_SystemUtils: isSystemApp Exception: android.content.pm.PackageManager$NameNotFoundException: com.huawei.appmarket
2021-06-17 11:38:54.886 31399-31399/com.chacon.dioone I/HMSSDK_UpdateManager: app is: com.huawei.appmarket;status is:NOT_INSTALLED
2021-06-17 11:38:54.888 31399-31399/com.chacon.dioone I/HMSSDK_UpdateManager: In getAndroidMarketSetting, configuration not found for android channel market setting.
2021-06-17 11:38:54.889 31399-31399/com.chacon.dioone I/HMSSDK_UpdateManager: typeList is empty, no upgrade solution
2021-06-17 11:38:54.897 31399-31399/com.chacon.dioone I/HMSSDK_BaseHmsClient: notifyFailed result: 26
2021-06-17 11:38:54.898 31399-31399/com.chacon.dioone I/HMSSDK_HuaweiApiManager: onConnectionFailed
2021-06-17 11:38:54.900 31399-31460/com.chacon.dioone I/HMSSDK_Util: available exist: true
2021-06-17 11:38:54.903 31399-31460/com.chacon.dioone I/HMSSDK_Util: available exist: true
2021-06-17 11:38:54.905 31399-31460/com.chacon.dioone E/HMSSDK_HmsInstanceIdEx: TokenTask failed, ErrorCode: 907135003
2021-06-17 11:38:54.908 31399-31460/com.chacon.dioone E/HMSSDK_HMSPackageManager: Failed to find HMS apk
2021-06-17 11:38:54.909 31399-31471/com.chacon.dioone E/HMSSDK_HMSPackageManager: Failed to find HMS apk
2021-06-17 11:38:54.915 31399-31460/com.chacon.dioone I/HMSSDK_BaseHmsClient: Enter disconnect, Connection Status: 5
2021-06-17 11:38:54.917 31399-31471/com.chacon.dioone E/HMSSDK_AutoInit: Push init failed
    com.huawei.hms.common.ApiException: 907135003: client api invalid
        at com.huawei.hms.opendevice.a.a(ErrorEnum.java:272)
        at com.huawei.hms.opendevice.i.doExecute(GetTokenTask.java:58)
        at com.huawei.hms.opendevice.i.doExecute(GetTokenTask.java:34)
        at com.huawei.hms.common.internal.TaskApiCall.onResponse(TaskApiCall.java:5)
        at com.huawei.hms.common.internal.HuaweiApiManager$ConnectionManager.innerConnectionFailed(HuaweiApiManager.java:23)
        at com.huawei.hms.common.internal.HuaweiApiManager$ConnectionManager.access$500(HuaweiApiManager.java:1)
        at com.huawei.hms.common.internal.HuaweiApiManager$ConnectionManager$2.run(HuaweiApiManager.java:1)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```
Thanks for your help.

**Comment by BsBrabi** [comment]
It looks like this is not an issue of ChoiceSDK. Probably you are accessing some HMS PushKit method when using a GMS device, and therefore HMS PushKit cannot initialize.

You can check if GMS or HMS is available with our `MobileServicesDetector` class, and prevent the method call on unsupported devices.

**Comment by aw4git** [comment]
Hi, thanks for your answer, it seems to be OK now ...
I just noticed that I still have this log error, 4 times: 
`E/HMSSDK_AGCUtils: Get appId with AGConnectServicesConfig failed`
even on Huawei device.

**Comment by BsBrabi** [comment]
Have you set the app id in your manifest file?
```xml
<meta-data
    android:name="com.huawei.hms.client.appid"
    android:value="appid=YOURAPPID" />
```

**Comment by aw4git** [comment]
Hi,
Yes, I confirmed appId is set in my manifest in the application section like this :
```
<meta-data
    android:name="com.huawei.hms.client.appid"
    android:value="appid=123456789" />
```
    
And the appId is the the same as the one set in in the agconnect-services.json file :
```
"app_info":{
		"app_id":"123456789",
		"package_name":"com.xxxxxx.yyyyyyyy"
},
```
